MarketPlaces/Models/StallHolders.cs
using System.ComponentModel.DataAnnotations;

namespace MarketPlaces.Models
{
    public class StallHolders
    {
        public int Id { get; set; }
        
        public ApplicationUser Stallholder { get; set; }
        [Required]
        public string StallholderId { get; set; }

        [Required]
        [StringLength(225)]
        public string Name { get; set; }
         [Required]
        [StringLength(225)]
        public string Product { get; set; }
    }
}

MarketPlaces/Controllers/StallHolderController.cs
using System.Web.Mvc;
using MarketPlaces.Models;
using MarketPlaces.ViewModels;
using Microsoft.AspNet.Identity;

namespace MarketPlaces.Controllers
{
    public class StallHolderController : Controller
    {
        private ApplicationDbContext _context;

        public StallHolderController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: StallHolder
        [Authorize]
        public ActionResult CreateStallHolder()
        {
            var viewModel = new StallHolderFormViewModel();
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStallHolder(StallHolderFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                // viewModel.Categories = _context.Categories.ToList();
                return View("CreateStallHolder", viewModel);
            }

           
            var stallholder = new StallHolders
            {
                //these are all the properties I want to display on the form 
                StallholderId = User.Identity.GetUserId(),
                Name = viewModel.Name,

                Product = viewModel.Product

            };
            _context.StallHolder.Add(stallholder);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

MarketPlaces/Views/StallHolder/CreateStallHolder.cshtml
@model MarketPlaces.ViewModels.StallHolderFormViewModel
@{
    ViewBag.Title = "CreateStallHolder";
}

<h2>Register a Stall</h2>

@using (Html.BeginForm("CreateStallHolder", "StallHolder"))
{
    <p class="alert alert-info">All fields are <strong>required</strong>.</p>
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(s => s.Name)
        @Html.TextBoxFor(s => s.Name, new { @class = "form-control", autofocus = "autofocus" })
        @Html.ValidationMessageFor(s => s.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(s => s.Product)
        @Html.TextBoxFor(s => s.Product, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Product)
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.Stallholder)
        @Html.TextBoxFor(s => s.Stallholder, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Stallholder)
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
}
@* This needs to come here to make sure that the jqueryval bundle comes after the jquery definition - prevents a request to the server *@
@section scripts
    {
    @Scripts.Render("~/bundles/jqueryval")
}