MarketPlaces/Models/Market.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

//This class creates the table for the database and each of the properties becomes a column.
//"Don't try to model the entire universe"  Build models as you need them.  Make small changes

namespace MarketPlaces.Models
{
    public class Market
    {
        public int Id { get; set; }

        public bool IsCancelled { get; private set; } //set 'set' to private for notifications

        //ApplicationUser is a preset class & is a navigation property
        public ApplicationUser Organiser { get; set; }
        //The 'Required' label makes the column 'not null'.  It wiil initially show an error because it needs a using statement.  if Resharper doesn't work right-click and choose resolve using statements
        [Required]

        public string OrganiserId { get; set; }

        //The 'string length' handle gives a limit to the nvarchar data type as it automatically sets to 'max'
        [Required]
        [StringLength(255)]
        public string Title { get; set; }

        public DateTime DateTime { get; set; }



        [Required]
        [StringLength(255)]
        public string Venue { get; set; }

        //make a model/class of categories - a navigation property
        public Category Category { get; set; }
        //and add foreign key properties
        [Required]
        public byte CategoryId { get; set; }

        // make the settor private so that once it is initialized, nowhere else can it be overwritten, creating a valid state
        public ICollection<Attendance> Attendances { get; private set; }

        //initialise attendances in a constructor:
        public Market()
        {
            Attendances = new Collection<Attendance>();
        }

        public void Cancel()
        {
            IsCancelled = true;

            var notification = Notification.MarketCancelled(this);

            foreach (var attendee in Attendances.Select(a => a.Attendee))
            {
                attendee.Notify(notification);
            }
        }

        public void Modify(DateTime dateTime, string venue, byte Category)
        {
            //a factory method is responsible for creating an object in a valid state
            var notification = Notification.MarketUpdated(this, DateTime, Venue);



            Venue = venue;
            DateTime = dateTime;
            CategoryId = Category;
            //iterate over attendees and notify them
            foreach (var attendee in Attendances.Select(a => a.Attendee))
                attendee.Notify(notification);

        }
    }
}

MarketPlaces/ViewModels/MarketsViewModel.cs
using System.Collections;
using System.Collections.Generic;
using MarketPlaces.Models;

namespace MarketPlaces.ViewModels
{
    public class MarketsViewModel : IEnumerable
    {
        public IEnumerable<Market> UpcomingMarkets { get; set; }
        public bool ShowActions { get; set; }
        public IEnumerator GetEnumerator()
        {
            throw new System.NotImplementedException();
        }
    }
}

MarketPlaces/Controllers/Api/MarketsController.cs
using System;
using MarketPlaces.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Http;

namespace MarketPlaces.Controllers.Api
{
    [Authorize]
    //accessible only by authenticated users
    public class MarketsController : ApiController
    {
        private ApplicationDbContext _context;

        public MarketsController()
        {
            _context = new ApplicationDbContext();
        }
        [HttpDelete]
        public IHttpActionResult Cancel(int id)
        {
            var userId = User.Identity.GetUserId();
            //get a given market.  Eager loading gets the market and all of its attendances  use the include method to eager load
            var market = _context.Markets
               //.Include(m => m.Attendances.Select(a => a.Attendee))// use the select method because Attendances is a collection and 'attendee' is not a property of Attendances
                .Single(m => m.Id == id && m.OrganiserId == userId);
           

            if (market.IsCancelled)
                return NotFound();
            
            market.Cancel();

             // market.IsCancelled = true;

            //The commented code is the process of refactoring, using cohesion to make sure highly related things are together.  Anything that changes the demain is not the responsibility of the controller but rather the domain model  so the above method is made to encapsulate all of the refactored code below

            //var notification = new Notification
            ////{
            ////    DateTime = DateTime.Now,
            ////    Market = market,
            ////    Type = NotificationType.MarketCancelled
            ////};
            // //var attendees = _context.Attendances.Where(a => a.MarketId == market.Id).Select(a => a.Attendee).ToList();

            // //foreach (var attendee in attendees)
            // foreach (var attendee in market.Attendances.Select(a => a.Attendee))
            //{
            // attendee.Notify(notification);
            ////    var userNotification = new UserNotification
            ////    {
            ////        User = attendee,
            ////        Notification = notification
            ////    };
            ////    _context.UserNotifications.Add(UserNotification);
            ////}
            _context.SaveChanges();
            //try
            //{
            //    
            //}
            //catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            //{
            //    Exception raise = dbEx;
            //    foreach (var validationErrors in dbEx.EntityValidationErrors)
            //    {
            //        foreach (var validationError in validationErrors.ValidationErrors)
            //        {
            //            string message = string.Format("{0}:{1}",
            //                validationErrors.Entry.Entity.ToString(),
            //                validationError.ErrorMessage);
            //            // raise a new exception nesting
            //            // the current instance as InnerException
            //            raise = new InvalidOperationException(message, raise);
            //        }
            //    }
            //    throw raise;
            //}
            return Ok();
        }
    }
}
//Cohesion - things that are highly related should  be together

MarketPlaces/Controllers/MarketsController.cs
using MarketPlaces.Models;
using MarketPlaces.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MarketPlaces.Controllers
{
    //An empty controller allows you to add all the code from scratch
    public class MarketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MarketsController()
        {
            //initialize _context
            _context = new ApplicationDbContext();
        }
        [Authorize]
        public ActionResult Mine()
        {
            var userId = User.Identity.GetUserId();
            var markets = _context.Markets
                .Where(m => m.OrganiserId == userId && m.DateTime > DateTime.Now && !m.IsCancelled)
                .Include(m => m.Category)
                .ToList();
            return View(markets);
        }

        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();
            var markets = _context.Attendances
                .Where(a => a.AttendeeId == userId)
                .Select(a => a.Market)
                .Include(m => m.Category)
                .ToList();
            var viewModel = new MarketsViewModel()
            {
                UpcomingMarkets = markets,
                ShowActions = User.Identity.IsAuthenticated
            };
            return View(viewModel);
        }
        //Initially this was the Index method but a new view was created and put into a folder in the views section that has been given the same name as the controller
        //Authorize allows only authenticated users to access the page
        [Authorize]
        public ActionResult Create()
        {
            //create a view model and set the categories property

            var viewModel = new MarketFormViewModel
            {
                Categories = _context.Categories.ToList(),
                Heading = "Add a Market"

            };
            // put the view model inside the view
            return View("MarketForm", viewModel);
        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            var market = _context.Markets.Single(m => m.Id == id && m.OrganiserId == userId);
            //create a view model and set the categories property

            var viewModel = new MarketFormViewModel
            {

                Heading = "Edit a Market",
                Id = market.CategoryId,
                Title = market.Title,
                Categories = _context.Categories.ToList(),
                Date = market.DateTime.ToString("d MMM yyyy"),
                Time = market.DateTime.ToString("HH:mm"),
                Category = market.CategoryId,
                Venue = market.Venue

            };
            // put the view model inside the view
            return View("MarketForm", viewModel);
        }
        [Authorize]//only authenticated users can access
        [HttpPost]
        [ValidateAntiForgeryToken]//validates the token in the create.cshtml. When the programme is run it creates a 'hidden field'(?) with a random token.  It also creates a cookie with an encrypted version of the token. Asp.Net compares the two to see if they match.  If they don't, it is an attack and will not proceed
                                  //The parameter holds the name of the model behind the view so that when the form is posted that is what we will get
        public ActionResult Create(MarketFormViewModel viewModel)
        {
            //Todo  fix this
            // THIS CODE DOES NOT WORK FOR ME!! It breaks the saving function even when all fields are correctly filled out.  It is saying it is not valid for some reason.
            // FIXED!! It was saying it wasn't valid because of the Create view above.  There was a validation error there.  Thank you Ryan.

            //Check to see if model is valid.  If it's not return the create view otherwise returnt he home view
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _context.Categories.ToList();
                return View("MarketForm", viewModel);
            }


            var market = new Market
            {
                //these are all the properties I want to display on the form 
                OrganiserId = User.Identity.GetUserId(),
                CategoryId = viewModel.Category,
                DateTime = viewModel.GetDateTime(),
                Title = viewModel.Title,
                Venue = viewModel.Venue

            };
            _context.Markets.Add(market);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");


        }
        [Authorize]//only authenticated users can access
        [HttpPost]
        [ValidateAntiForgeryToken]//validates the token in the create.cshtml. When the programme is run it creates a 'hidden field'(?) with a random token.  It also creates a cookie with an encrypted version of the token. Asp.Net compares the two to see if they match.  If they don't, it is an attack and will not proceed
                                  //The parameter holds the name of the model behind the view so that when the form is posted that is what we will get
        public ActionResult Update(MarketFormViewModel viewModel)
        {
            //Check to see if model is valid.  If it's not return the create view otherwise returnt he home view
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _context.Categories.ToList();
                return View("MarketForm", viewModel);
            }
            var UserId = User.Identity.GetUserId();
            var market = _context.Markets
                .Include(m => m.Attendances.Select(a => a.Attendee))
                .Single(m => m.Id == viewModel.Id && m.OrganiserId == UserId);
           // market.Modify(viewModel.GetDateTime(), viewModel.Venue, viewModel.Category);

            _context.SaveChanges();
            return RedirectToAction("Index", "Home");


        }
        [HttpPost]
        public ActionResult Details()
        {
            var upcomingMarkets = _context.Markets

                .Include(m => m.Category)
                .Include(m => m.Organiser).OrderBy(m => m.DateTime)
                .Where(m => m.DateTime > DateTime.Now).ToList();
            var viewModel = new MarketsViewModel
            {
                UpcomingMarkets = upcomingMarkets,

            };

            return RedirectToAction("Details");
        }

       

    }
}

MarketPlaces/Views/Markets/Attending.cshtml
@model MarketPlaces.ViewModels.MarketsViewModel
@{
    ViewBag.Title = "Attending";
}
@* At this stage,  I could be using a shared view -Marketscshtml - but I want to use a slightly different view. The difference is that in this view, I don't want to display the organiser name*@
<h2>Markets I'm Attending</h2>
<ul class="markets">
    @foreach (var market in Model.UpcomingMarkets)
    {
        <li>
            <div class="date">
                <div class="month">
                    @market.DateTime.ToString(("MMM"))
                </div>
                <div class="day">
                    @market.DateTime.ToString("d ")
                </div>
            </div>
            <div class="details">
                <span class="title">
                    @market.Title
                    @if (Model.ShowActions)
                    {
                        <button data-market-id="@market.Id " class="btn btn-link btn-sm js-toggle-follow">Follow</button>
                    }

                </span>
                <span class="venue">
                    @market.Venue
                    @if (Model.ShowActions)
                    {
                        @*<button class="btn btn-default btn-sm pull-right js-toggle-attendance" data-market-id="@market.Id">Going</button>*@
                    }
                </span>
            </div>
            <div class+="extra details">
                <span class="category">
                    <span class="newTitles">Theme</span>  @market.Category.Name

                </span>
            </div>
           





        </li>
    }
</ul>

MarketPlaces/Views/Markets/Create.cshtml
@* The first thing to do to create a new view is to specify the model behind the view (that changed to a view model later in the process of building the project)A view model is used when what is presented to the user is different from the model of the domain e.g. date and time  Another name for view nmodel is presentation model.  It is not part of the domain  *@
@model MarketPlaces.ViewModels.MarketFormViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Add a Market</h2>

@using (Html.BeginForm("Create", "Markets"))

{ 
    <p class="alert alert-info">All fields are <strong>required</strong>.</p>
    
    //Place an antiforgery token here to prevent csrf attacks -cross-site request forgery which allows an attacker to perform actions on behalf of a user without their knowledge. eg. Creating markets on behalf of an organiiser without their knowledge
        @Html.AntiForgeryToken()
    //Bootstrap has layout classes to use to create different looks.  - Google Bootstrap to find them.  E.g. .form-group wraps labels and controls with preset, optimum, spacing;  'form-control'  changes the look of the text box. Each div creates a new 'block' of labels and contseparates the different components onto a different 'line'
    //add validation message place holder for each property
      
<div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", autofocus = "autofocus" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Venue)
        @Html.TextBoxFor(m => m.Venue, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Venue)
    </div>
        //A place holder is used to show the user which format to use for date and time
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control", placeholder = "eg 1 Dec 2016" })
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control", placeholder = "eg 20:00" })
        @Html.ValidationMessageFor(m => m.Time)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @*//add a "" to create an empty space at the top of the drop down list*@
        @Html.ValidationMessageFor(m => m.Category)
    </div>
        //all buttons are part of the btn class and there are secondary classes to determine colour - which can be changed.  Primary button is for primary actions on a page.  The label goes between the > <
        <button type="submit" class="btn btn-primary">Save</button>

}
@*//Add the bundle for client side validation.  Needs to come here so that it comes after the jquery bundle.  *@
@section scripts
    {
    @Scripts.Render("~/bundles/jqueryval")
}

MarketPlaces/Views/Markets/Details.cshtml
@model MarketPlaces.ViewModels.MarketsViewModel
@{
    ViewBag.Title = "Details";
}
@* a new view to expand the details being displayed Todo: Add list of registered stalls *@
<h2>Details</h2>

<ul class="markets voffset4">
    @foreach (var market in Model.UpcomingMarkets)
    {
        <li>
            <div class="date">
                <div class="month">
                    @market.DateTime.ToString(("MMM"))
                </div>
                <div class="day">
                    @market.DateTime.ToString("d ")
                </div>
                <div class="month">
                    @market.DateTime.ToString(("HH:mm"))
                </div>
            </div>
            <div class="details">
                <span class="title">
                    @market.Title  <button data-market-id="@market.Id " class="btn btn-default btn-sm pull-right js-toggle-attendance markets voffset6">Going ?</button>
                    @* "pull-right" only pulls it in line with the edge of the div it is in.  If divs have different length information, the buttons will be all over the place, lining up with whatever text they are with *@
                </span>

                <span class="venue">
                    @*<span class="newTitles">Venue:</span>*@    @market.Venue
                </span>
                <br />
                <span class="category">
                    @*<span class="newTitles">Theme</span>*@  @market.Category.Name
                </span>
            </div>
            <div class+="extra details">

            </div>
            <span class="organiser">
                        <span class="newTitles">Organiser:</span>  @market.Organiser.Name
                    </span>





        </li>
    }
</ul>
@section scripts
{
    @* When the document is loaded subscribe to the click event of the button - toggle_attendance means that the button can be used to add or delete attendance  *@
    <script>
        $(document).ready(function() {
            $(".js-toggle-attendance").click(function (e) {
                var button = $(e.target);
                $.post("/api/attendances", { marketId: button.attr("data-market-id") })
                    .done(function() {
                        button
                            //change the colour of the button when it is clicked: remove the default, white, colour, add the 'info', blue, colour and change the text
                            .removeClass("btn-default")
                            .addClass("btn-info")
                            .text("Going");
                    })
                    .fail(function() {
                        alert("Something failed");

                    });
            });
        })
    </script>

MarketPlaces/Views/Markets/MarketForm.cshtml
@* The first thing to do to create a new view is to specify the model behind the view (that changed to a view model later in the process of building the project)A view model is used when what is presented to the user is different from the model of the domain e.g. date and time  Another name for view nmodel is presentation model.  It is not part of the domain  *@
@model MarketPlaces.ViewModels.MarketFormViewModel
@{
    ViewBag.Title = Model.Heading;
}

<h2>@Model.Heading</h2>

@using (Html.BeginForm(Model.Action, "Markets"))

{ 
    <p class="alert alert-info">All fields are <strong>required</strong>.</p>
    
    //Place an antiforgery token here to prevent csrf attacks -cross-site request forgery which allows an attacker to perform actions on behalf of a user without their knowledge. eg. Creating markets on behalf of an organiiser without their knowledge
        @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    //Bootstrap has layout classes to use to create different looks.  - Google Bootstrap to find them.  E.g. .form-group wraps labels and controls with preset, optimum, spacing;  'form-control'  changes the look of the text box. Each div creates a new 'block' of labels and contseparates the different components onto a different 'line'
    //add validation message place holder for each property
      
<div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", autofocus = "autofocus" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Venue)
        @Html.TextBoxFor(m => m.Venue, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Venue)
    </div>
        //A place holder is used to show the user which format to use for date and time
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control", placeholder = "eg 1 Dec 2016" })
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control", placeholder = "eg 20:00" })
        @Html.ValidationMessageFor(m => m.Time)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @*//add a "" to create an empty space at the top of the drop down list*@
        @Html.ValidationMessageFor(m => m.Category)
    </div>
        //all buttons are part of the btn class and there are secondary classes to determine colour - which can be changed.  Primary button is for primary actions on a page.  The label goes between the > <
        <button type="submit" class="btn btn-primary">Save</button>

}
@*//Add the bundle for client side validation.  Needs to come here so that it comes after the jquery bundle.  *@
@section scripts
    {
    @Scripts.Render("~/bundles/jqueryval")
}

MarketPlaces/Views/Markets/Mine.cshtml
@model IEnumerable<MarketPlaces.Models.Market>
@{
    ViewBag.Title = "Mine";
}

<h2>My Upcoming Markets</h2>

<ul class="markets voffset4">
    @foreach (var market in Model)
    {
        <li>
            <div class="date">
                <div class="month">
                    @market.DateTime.ToString(("MMM"))
                </div>
                <div class="day">
                    @market.DateTime.ToString("d ")
                </div>
                <div class="month">
                    @market.DateTime.ToString(("HH:mm"))
                </div>
            </div>
            <div class="details">
                <span class="title">
                    @market.Title  @*<button data-market-id="@market.Id " class="btn btn-default btn-sm pull-right js-details markets voffset6">Going?</button>*@
                    @* "pull-right" only pulls it in line with the edge of the div it is in.  If divs have different length information, the buttons will be all over the place, lining up with whatever text they are with *@
                </span>

                <span class="venue">
                    @*<span class="newTitles">Venue:</span>*@    @market.Venue
                </span>
                <br />
                <span class="category">
                    @*<span class="newTitles">Theme</span>*@  @market.Category.Name
                </span>
                <div class="actions">
                    <a href="@Url.Action("Edit", "Markets", new {id = market.Id})">
                        Edit
                    </a> |
                    <a href="#" class="js-cancel-market" data-market-id="@market.Id">
                        Cancel
                    </a>
                </div>
           
               
            </div>






        </li>
    }
</ul>
@section scripts
{
    <script>
        //when document is ready the specified function will be called
        $(document)
            .ready(function() {
                $(".js-cancel-market")
                    .click(function(e) {
                        //e represents the click event
                        var link = $(e.target);
                        //ask user for confirmation
                        bootbox.dialog({
                            message: "Are you sure you want to cancel this market?",
                            title: "Confirm",
                            buttons: {
                                no: {
                                    label: "No",
                                    className: "btn-default",
                                    callback: function() {
                                        bootbox.hideAll();
                                    }
                                },
                                yes: {
                            label: "Yes",
                            className: "btn-danger",
                            callback: function() {
                                $.ajax({
                                    url: "/api/markets/" + link.attr("data-market-id"),
                                    method: "DELETE" //HttpDelete

                                })
                                  .done(function() {
                                      //The li that represents the market
                                      link.parents("li")
                                          .fadeOut(function() {
                                              $(this).remove();
                                          });
                                  })
                                  .fail(function() {
                                      alert("Something failed!");
                                  });
                                }
                              }
                            }
                        });
                     });    
                  });
                   
    </script>
}